# --- VARIABLES ---

FRONTEND_DIR=frontend
BACKEND_DIR=backend
OUTPUT_BIN=$(BACKEND_DIR)/pihole-cluster-admin

# --- TASKS ---

.PHONY: help dev build prod run-prod clean init

help:
	@echo "Common tasks:"
	@echo "  make dev         - Start Vite + Go backend in dev mode (proxy to Vite)"
	@echo "  make build       - Build Go backend (dev mode, no embed)"
	@echo "  make prod        - Build frontend and backend (with embedded static files)"
	@echo "  make run-prod    - Run the production binary locally"
	@echo "  make clean       - Remove generated build artifacts"

dev:
	@echo "Running dev mode: Vite + Go (with reverse proxy)"
	cd $(FRONTEND_DIR) && npm run dev & \
	go run -tags=dev ./$(BACKEND_DIR)

build:
	@echo "Building Go backend in dev mode..."
	go build -tags=dev -o $(OUTPUT_BIN) ./$(BACKEND_DIR)

prod:
	@echo "Building frontend..."
	npm install --prefix $(FRONTEND_DIR)
	npm run build --prefix $(FRONTEND_DIR)

	@echo "Copying frontend build into backend/ for embedding..."
	rm -rf $(BACKEND_DIR)/dist
	cp -r $(FRONTEND_DIR)/dist $(BACKEND_DIR)/dist

	@echo "Building Go backend with embedded frontend..."
	cd $(BACKEND_DIR) && go build -o pihole-cluster-admin

run-prod: prod
	@echo "Running production binary..."
	./$(BACKEND_DIR)/pihole-cluster-admin

clean:
	@echo "Cleaning build output..."
	rm -f $(OUTPUT_BIN)
	rm -rf $(FRONTEND_DIR)/dist

init:
	@echo "Creating .devcontainer/.env with default configuration..."
	@mkdir -p .devcontainer
	@echo "# Auto-DNS WebUI Configuration" > .devcontainer/.env
	@echo "# Generated by make init - modify as needed" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Application Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_APP_HOSTNAME=pihole-cluster-admin.local" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Server Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PORT=8080" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Development Proxy Configuration (for dev mode)" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PROXY_ENABLE=true" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PROXY_HOSTNAME=localhost" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_SERVER_PROXY_PORT=5173" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Etcd Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_HOST=etcd" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_PORT=2379" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_PATH_PREFIX=/skydns" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_LOCK_TTL=5.0" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_LOCK_TIMEOUT=2.0" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_ETCD_LOCK_RETRY_INTERVAL=0.1" >> .devcontainer/.env
	@echo "" >> .devcontainer/.env
	@echo "# Logging Configuration" >> .devcontainer/.env
	@echo "AUTO_DNS_WEBUI_LOG_LEVEL=INFO" >> .devcontainer/.env
	@echo "Created .devcontainer/.env with default configuration"
