database:
  path: .devcontainer/data/data.db
  migrations_path: backend/internal/migrations

encryption_key: secret-do-not-commit-in-production

log:
  level: DEBUG

server:
  port: 8081
  proxy:
    enable: true
    hostname: localhost
    port: 5173
