services:
  pihole-node1:
    image: pihole/pihole:latest
    container_name: pihole-node1-dev
    hostname: pihole-node1-dev
    networks:
      pihole-cluster-admin-net:
        aliases: [pihole-node1]
    volumes:
      - pihole_node1_etc:/etc/pihole
      - pihole_node1_dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ:-UTC}
      FTLCONF_webserver_api_password: changeme1 # ⚠️ Dev-only — do not commit secrets
    ports:
      - "8082:80"
    restart: unless-stopped
    env_file:
      - .env

  pihole-node2:
    image: pihole/pihole:latest
    container_name: pihole-node2-dev
    hostname: pihole-node2-dev
    networks:
      pihole-cluster-admin-net:
        aliases: [pihole-node2]
    volumes:
      - pihole_node2_etc:/etc/pihole
      - pihole_node2_dnsmasq:/etc/dnsmasq.d
    environment:
      TZ: ${TZ:-UTC}
      FTLCONF_webserver_api_password: changeme2 # ⚠️ Dev-only — do not commit secrets
    ports:
      - "8083:80"
    restart: unless-stopped
    env_file:
      - .env

  pihole-cluster-admin:
    build:
      context: ..
      dockerfile: ./Dockerfile
      target: dev
    ports:
      - "${PIHOLE_CLUSTER_ADMIN_SERVER_PORT:-8081}:${PIHOLE_CLUSTER_ADMIN_SERVER_PORT:-8081}"
      - "5174:5173"
      - "8081:8081"
    volumes:
      - ..:/workspace
    networks:
      - pihole-cluster-admin-net
    command: sleep infinity
    env_file:
      - .env

networks:
  pihole-cluster-admin-net:
    driver: bridge


volumes:
  pihole_node1_etc: {}
  pihole_node1_dnsmasq: {}
  pihole_node2_etc: {}
  pihole_node2_dnsmasq: {}
