log:
  level: DEBUG

server:
  port: 8081
  
piholes:
  - id: dns1
    host: 192.168.1.100
    port: 80
    password: changeme1
    scheme: http
  - id: dns2
    host: 192.168.1.101
    port: 80
    password: changeme2
    scheme: http
